language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

osx_image: xcode7.3
sudo: false
dist: trusty

env:
  global:
    - ERT_SHOW_BACKTRACE=1
    - LD_LIBRARY_PATH="$(pwd)/install/lib64"
  matrix:
    - PYTHON_VERSION=2.7 TEST_SUITE="-LE SLOW"  # Run all tests not labeled as slow
    - PYTHON_VERSION=2.7 TEST_SUITE="-L SLOW_1" # Run all tests labeled as SLOW in group 1
    - PYTHON_VERSION=2.7 TEST_SUITE="-L SLOW_2" # Run all tests labeled as SLOW in group 2
    - PYTHON_VERSION=2.7 TEST_SUITE=""          # TODO: Can be removed when libres is MacOS compliant
    - PYTHON_VERSION=3.6                        # Run all testsliant

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang
    # TODO: The excludes below should be removed after MacOS is supported
    - os: linux
      env: PYTHON_VERSION=2.7 TEST_SUITE=""
    - os: osx
      env: PYTHON_VERSION=2.7 TEST_SUITE="-LE SLOW"
    - os: osx
      env: PYTHON_VERSION=2.7 TEST_SUITE="-L SLOW_1"
    - os: osx
      env: PYTHON_VERSION=2.7 TEST_SUITE="-L SLOW_2"


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
      - sourceline: 'ppa:opm/ppa'
    packages:
      - libopm-simulators
      - liblapack-dev
      - valgrind
      - gcc-4.8
      - g++-4.8
      - clang
      - cmake
      - cmake-data

install:
    - if [[ "$CC" == "gcc" ]]; then export CXX="g++-4.8"; fi
    - cmake --version
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        export CONDA_OS=MacOSX;
      else
        export CONDA_OS=Linux;
      fi
    - if [[ $PYTHON_VERSION == 2.7 ]]; then
        export TRAVIS_PYTHON_VERSION="2.7";
      else
        export TRAVIS_PYTHON_VERSION="3.6";
      fi
    # We do this conditionally because it saves us some downloading if the version is the same.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-${CONDA_OS}-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-4.4.10-${CONDA_OS}-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export CONDA_HOME="$HOME/miniconda"
    - export PATH="$CONDA_HOME/bin:$PATH"
    - pip install -r requirements.txt
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    - wget https://raw.githubusercontent.com/Statoil/ert/master/travis/install_python_packages.py
    - python install_python_packages.py

before_script:
  - wget https://raw.githubusercontent.com/Statoil/ert/master/travis/build_total.py

script:
  - python --version
  - python build_total.py res ${TEST_SUITE}

